# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asset_check_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssetCheckDialog(object):
    def setupUi(self, AssetCheckDialog):
        AssetCheckDialog.setObjectName("AssetCheckDialog")
        AssetCheckDialog.resize(700, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AssetCheckDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.commit_log_error_label = QtWidgets.QLabel(AssetCheckDialog)
        self.commit_log_error_label.setText("")
        self.commit_log_error_label.setObjectName("commit_log_error_label")
        self.verticalLayout.addWidget(self.commit_log_error_label)
        self.commit_log_label = QtWidgets.QLabel(AssetCheckDialog)
        self.commit_log_label.setObjectName("commit_log_label")
        self.verticalLayout.addWidget(self.commit_log_label)
        self.commit_log_text_edit = QtWidgets.QTextEdit(AssetCheckDialog)
        self.commit_log_text_edit.setObjectName("commit_log_text_edit")
        self.verticalLayout.addWidget(self.commit_log_text_edit)
        self.output_label = QtWidgets.QLabel(AssetCheckDialog)
        self.output_label.setObjectName("output_label")
        self.verticalLayout.addWidget(self.output_label)
        self.output_plain_text_edit = QtWidgets.QPlainTextEdit(AssetCheckDialog)
        self.output_plain_text_edit.setObjectName("output_plain_text_edit")
        self.verticalLayout.addWidget(self.output_plain_text_edit)
        self.op_button_box = QtWidgets.QDialogButtonBox(AssetCheckDialog)
        self.op_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.op_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.op_button_box.setObjectName("op_button_box")
        self.verticalLayout.addWidget(self.op_button_box)

        self.retranslateUi(AssetCheckDialog)
        self.op_button_box.accepted.connect(AssetCheckDialog.accept) # type: ignore
        self.op_button_box.rejected.connect(AssetCheckDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AssetCheckDialog)

    def retranslateUi(self, AssetCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        AssetCheckDialog.setWindowTitle(_translate("AssetCheckDialog", "资产检查"))
        self.commit_log_label.setText(_translate("AssetCheckDialog", "提交日志"))
        self.output_label.setText(_translate("AssetCheckDialog", "资产检查信息"))
